services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_INITDB_DATABASE=neuron'
      - 'MYSQL_INITDB_PASSWORD=glgjss17yfhbqz'
      - 'MYSQL_INITDB_USERNAME=root'
    ports:
      - '3306'
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=neuron'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
