server:
  port: 8080
spring:
  application:
    name: neuron
  # mysql数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/neuron?characterEncoding=utf-8
    username: root
    password: glgjss17yfhbqz
  # Mongodb数据库配置

  # Redis数据库配置
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  # JWT 存储的请求头
  tokenHeader: Authorization
  # JWT 加解密使用的密钥
  secret: 9002ad1588e0dd489b2b2045004b6ca7914b39f8dfc427888ac8ffd1527a66a3
  # JWT refresh_token 的过期时间，单位秒，604800 = 7天
  refresh_expiration: 604800
  # JWT access_token 的过期时间，单位秒，3600 = 1小时
  access_expiration: 3600
  # JWT 的开头
  tokenHead: 'Bearer '

